### ISSUE TITLE
Panicked, Image index out of bounds error

### ISSUE THREAD

**Issue by jbutz** [codepunkt/gatsby-remark-opengraph#2]
I'm trying to make use of the plugin and am running into some errors, I've included the error below as well as the script I have that replicates the issue. I'm doing this work on a Mac with an Apple M1 Pro processor. This may be an an issue that belongs on your [codepunkt/wasm-layout-text project](https://github.com/codepunkt/wasm-layout-text).

Can you provide any guidance?

```
panicked at 'Image index (2, 4294967244) out of bounds (1200, 630)', /home/christoph/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.22.5/./src/buffer.rs:733:21

Stack:

Error
    at module.exports.__wbg_new_59cb74e423758ede (/workspace/node_modules/@codepunkt/wasm-layout-text/wasm_layout_text.js:303:15)
    at wasm://wasm/0006e902:wasm-function[40]:0xde44
    at wasm://wasm/0006e902:wasm-function[177]:0x12712
    at wasm://wasm/0006e902:wasm-function[77]:0x10e03
    at wasm://wasm/0006e902:wasm-function[140]:0x123b1
    at wasm://wasm/0006e902:wasm-function[119]:0x11fdf
    at wasm://wasm/0006e902:wasm-function[127]:0x12193
    at wasm://wasm/0006e902:wasm-function[73]:0x10a67
    at wasm://wasm/0006e902:wasm-function[10]:0x3bc0
    at wasm://wasm/0006e902:wasm-function[11]:0x55a7


Error RuntimeError: unreachable
    at wasm://wasm/0006e902:wasm-function[77]:0x10e22
    at wasm://wasm/0006e902:wasm-function[140]:0x123b1
    at wasm://wasm/0006e902:wasm-function[119]:0x11fdf
    at wasm://wasm/0006e902:wasm-function[127]:0x12193
    at wasm://wasm/0006e902:wasm-function[73]:0x10a67
    at wasm://wasm/0006e902:wasm-function[10]:0x3bc0
    at wasm://wasm/0006e902:wasm-function[11]:0x55a7
    at module.exports.render (/workspace/node_modules/@codepunkt/wasm-layout-text/wasm_layout_text.js:141:14)
    at /workspace/node_modules/gatsby-remark-opengraph/src/index.js:99:24
    at Array.map (<anonymous>)
```

```
const { createImage } = require('gatsby-remark-opengraph');

createImage({
  background: '#bada55',
  texts: [
    {
      text: 'Hello world!',
      color: '#ffffff',
      font: require.resolve(
        '/workspace/src/assets/Merriweather/Merriweather-Regular.ttf'
      ),
      verticalAlign: 'bottom',
    },
  ],
})
  .then((r) => {
    console.log('Results', r);
  })
  .catch((e) => {
    console.error('Error', e);
  });
```

**Comment by decompil3d** [comment]
I ran into this same problem and spent a while debugging into the Rust code. The problem is that you are vertically aligning to the bottom, but starting your text at `y = 0` since you don't explicitly declare a `y` value. This leads the code to attempt to position your text at a negative `y` position (0 - the height of each glyph) and it panics.

The solution is to explicitly set a `y` value on your `Text` objects -- probably to whatever the height of your image is minus some amount of padding.
